name: 'Setup Development Environment'
description: 'Sets up Node.js, dependencies and development tools'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  install-pkg:
    description: 'Whether to install pkg globally'
    required: false
    default: 'false'
  install-packer:
    description: 'Whether to install Packer'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      shell: bash
      run: npm ci
    
    - name: Install pkg Globally
      if: ${{ inputs.install-pkg == 'true' }}
      shell: bash
      run: npm install -g pkg
    
    - name: Install Packer
      if: ${{ inputs.install-packer == 'true' }}
      uses: hashicorp/setup-packer@v2
      with:
        version: latest