name: 'Build Application Binary'
description: 'Creates a NodeJS application binary using pkg'

inputs:
  output-path:
    description: 'Path to store the binary'
    required: false
    default: 'infra/packer/dist'
  binary-name:
    description: 'Name of the binary file'
    required: false
    default: 'webapp'
  node-version:
    description: 'Node.js version'
    required: false
    default: '18'

runs:
  using: "composite"
  steps:
    - name: Create Output Directory
      shell: bash
      run: mkdir -p ${{ inputs.output-path }}
    
    - name: Build Binary
      shell: bash
      run: |
        # Build the executable
        pkg server.js --output ${{ inputs.output-path }}/${{ inputs.binary-name }} --targets node${{ inputs.node-version }}-linux-x64
        chmod +x ${{ inputs.output-path }}/${{ inputs.binary-name }}
        
        # Verify build success
        if [ -f ${{ inputs.output-path }}/${{ inputs.binary-name }} ]; then
          echo "Build complete! Binary located at ${{ inputs.output-path }}/${{ inputs.binary-name }}"
        else
          echo "Build failed!"
          exit 1
        fi