name: Validate Packer Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_packer:
    name: Validate Packer Script
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Install pkg globally
        run: npm install -g pkg
        
      - name: Build Application with pkg
        run: |
          # Create the output directory if it doesn't exist
          mkdir -p infra/packer/dist
          
          # Build the binary
          pkg server.js --output infra/packer/dist/webapp --targets node18-linux-x64
          
          # Make it executable
          chmod +x infra/packer/dist/webapp
          
          # Verify the binary was created
          if [ -f infra/packer/dist/webapp ]; then
            echo " Build complete! Binary located at infra/packer/dist/webapp"
          else
            echo "Build failed! Binary not found"
            exit 1
          fi
      
      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest
      
      - name: Initialize Packer
        working-directory: infra/packer
        run: packer init .
      
      - name: Check Packer Formatting
        working-directory: infra/packer
        run: |
          if packer fmt -check -diff .; then
            echo " Packer format is correct."
          else
            echo "Packer format check failed. Run 'packer fmt' locally to fix formatting."
            exit 1
          fi
      
      - name: Validate Packer Configuration
        working-directory: infra/packer
        run: packer validate machine-image.pkr.hcl