name: WebApp CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  run-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: '18'
      
      - name: Start MySQL
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          docker run --name mysql-test \
            -e DB_PASSWORD="${DB_PASSWORD}" \
            -e DB_NAME="${DB_NAME}" \
            -p 3306:3306 \
            -d mysql:8.0
          
          # Wait for MySQL to start without exposing password in logs
          echo "Waiting for MySQL to start..."
          for i in {30..0}; do
            if docker exec mysql-test mysqladmin ping -h localhost -p"${DB_PASSWORD}" --silent 2>/dev/null; then
              echo "MySQL is up and running"
              break
            fi
            echo "Still waiting..."
            sleep 2
          done
          if [ "$i" = 0 ]; then
            echo "ERROR: MySQL failed to start"
            exit 1
          fi
          
      - name: Create Environment File
        run: |
          cat <<EOF > .env
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          PORT=${{ secrets.PORT }}
          S3_BUCKET_NAME=test-bucket
          EOF
          
      - name: Run Tests
        run: npm test
      
      - name: Report Test Status
        if: always()
        run: echo "::notice::Unit tests completed with status ${{ job.status }}"
        
      - name: Cleanup MySQL Container
        if: always()
        run: docker rm -f mysql-test || true

  validate_packer:
    name: Validate Packer Script
    runs-on: ubuntu-latest
    needs: run-tests
    if: success() || failure()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: '18'
          install-pkg: 'true'
          install-packer: 'true'
        
      - name: Build Binary
        uses: ./.github/actions/build-binary
        with:
          output-path: 'infra/packer/dist'
          binary-name: 'webapp'
          node-version: '18'
      
      - name: Debug Information
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "PR Number: ${{ github.event.number }}"
          echo "List workflow files:"
          find .github -type f | sort
          
      - name: Copy Service File to Packer Directory
        run: |
          # Ensure the packer directory exists
          mkdir -p infra/packer
          # Copy webapp.service to the packer directory
          cp infra/packer/webapp.service infra/packer/ || echo "Service file already in place"
          
      - name: Initialize Packer
        working-directory: infra/packer
        run: packer init .
      
      - name: Check Packer Formatting
        working-directory: infra/packer
        run: |
          if packer fmt -check -diff .; then
            echo "Packer format is correct."
          else
            echo "Packer format check failed. Run 'packer fmt' locally to fix formatting."
            exit 1
          fi
      
      - name: Validate Packer Configuration
        working-directory: infra/packer
        run: |
          packer validate \
            -var "target_account_id=dummy-account" \
            -var "gcp_dev_project=dummy-project" \
            -var "gcp_target_project=dummy-project" \
            -var "aws_build_region=us-east-1" \
            -var "gcp_build_zone=us-east1-b" \
            -var "aws_vm_size=t2.micro" \
            -var "gcp_vm_type=e2-medium" \
            -var "gcp_storage_region=us" \
            machine-image.pkr.hcl
      
      - name: Workflow Summary
        if: always()
        run: |
          echo "## WebApp CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "* Unit Tests: ${{ needs.run-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "* Packer Validation: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "* Pull Request: #${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY